appName: currencyservice
appImage: gcr.io/google-samples/microservices-demo/currencyservice
appVersion: v0.2.3
replicaCount: 2
containerEnvVars:
  - name: PORT
    value: "7000"
    
serviceType: ClusterIP
servicePort: 7000
containerPort: 7000