appName: emailservice
appImage: gcr.io/google-samples/microservices-demo/emailservice
appVersion: v0.2.3
replicaCount: 2
containerEnvVars:
  - name: PORT
    value: "8080"
  - name: DISABLE_TRACING
    value: "1"
  - name: DISABLE_PROFILER
    value: "1"    

serviceType: ClusterIP
servicePort: 5000
containerPort: 8080